packages:
  - packages/*
  - tooling/*

catalog:
  typescript: ^5.6.3
  eslint: ^9.19.0
  prettier: ^3.5.3
  tailwindcss: ^4.0.3

catalogs:
  react:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': 19.0.8
    '@types/react-dom': 19.0.3
