packages:
  - packages/*
  - tooling/*
catalog:
  typescript: ^5.6.3
  eslint: ^9.24.0
  prettier: ^3.5.3
  tailwindcss: ^4.1.3
catalogs:
  react:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': 19.1.0
    '@types/react-dom': 19.1.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
