export { default as Root } from '@/components/table/Table'
export { default as Body } from '@/components/table/TableBody'
export { default as Cell } from '@/components/table/TableCell'
export { default as Column } from '@/components/table/TableColumn'
export { default as Head } from '@/components/table/TableHead'
export { default as Row } from '@/components/table/TableRow'
